export const SAVE_PRE_EMPLOYMENT = "SAVE_PRE_EMPLOYMENT";
export const SAVE_EDUCATION = "SAVE_EDUCATION";
export const SAVE_EXPERIENCE = "SAVE_EXPERIENCE";
export const SAVE_REFERENCES = "SAVE_REFERENCES";
export const SAVE_SKILLS = "SAVE_SKILLS";
export const SAVE_DOCUMENTS = "SAVE_DOCUMENTS";
export const SAVE_CERTIFICATION = "SAVE_CERTIFICATION";
export const SAVE_AVAILABILITY = "SAVE_AVAILABILITY";

export const SUBMIT_APPLICATION_REQUEST = "SUBMIT_APPLICATION_REQUEST";
export const SUBMIT_APPLICATION_SUCCESS = "SUBMIT_APPLICATION_SUCCESS";
export const SUBMIT_APPLICATION_FAILURE = "SUBMIT_APPLICATION_FAILURE";


export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";

export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";
export const ADMIN_LOGOUT_FAILURE = "ADMIN_LOGOUT_FAILURE";

export const FETCH_APPLICANTS_REQUEST = "FETCH_APPLICANTS_REQUEST";
export const FETCH_APPLICANTS_SUCCESS = "FETCH_APPLICANTS_SUCCESS";
export const FETCH_APPLICANTS_FAILURE = "FETCH_APPLICANTS_FAILURE";

export const DELETE_APPLICANT_REQUEST = "DELETE_APPLICANT_REQUEST";
export const DELETE_APPLICANT_SUCCESS = "DELETE_APPLICANT_SUCCESS";
export const DELETE_APPLICANT_FAILURE = "DELETE_APPLICANT_FAILURE";

// Fetching all applications
export const FETCH_ADMIN_APPS_REQUEST = "FETCH_ADMIN_APPS_REQUEST";
export const FETCH_ADMIN_APPS_SUCCESS = "FETCH_ADMIN_APPS_SUCCESS";
export const FETCH_ADMIN_APPS_FAILURE = "FETCH_ADMIN_APPS_FAILURE";

// Deleting an application
export const DELETE_ADMIN_APP_REQUEST = "DELETE_ADMIN_APP_REQUEST";
export const DELETE_ADMIN_APP_SUCCESS = "DELETE_ADMIN_APP_SUCCESS";
export const DELETE_ADMIN_APP_FAILURE = "DELETE_ADMIN_APP_FAILURE";

// Fetching single application details (For the View Eye icon)
export const FETCH_APP_DETAILS_REQUEST = "FETCH_APP_DETAILS_REQUEST";
export const FETCH_APP_DETAILS_SUCCESS = "FETCH_APP_DETAILS_SUCCESS";
export const FETCH_APP_DETAILS_FAILURE = "FETCH_APP_DETAILS_FAILURE";