export const SAVE_PRE_EMPLOYMENT = "SAVE_PRE_EMPLOYMENT";
export const SAVE_EDUCATION = "SAVE_EDUCATION";
export const SAVE_EXPERIENCE = "SAVE_EXPERIENCE";
export const SAVE_REFERENCES = "SAVE_REFERENCES";
export const SAVE_SKILLS = "SAVE_SKILLS";
export const SAVE_DOCUMENTS = "SAVE_DOCUMENTS";
export const SAVE_CERTIFICATION = "SAVE_CERTIFICATION";
export const SAVE_AVAILABILITY = "SAVE_AVAILABILITY";

export const SUBMIT_APPLICATION_REQUEST = "SUBMIT_APPLICATION_REQUEST";
export const SUBMIT_APPLICATION_SUCCESS = "SUBMIT_APPLICATION_SUCCESS";
export const SUBMIT_APPLICATION_FAILURE = "SUBMIT_APPLICATION_FAILURE";

export const CLEAR_AUTH_ERRORS = "CLEAR_AUTH_ERRORS";


export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILURE = "ADMIN_LOGIN_FAILURE";

export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";
export const ADMIN_LOGOUT_FAILURE = "ADMIN_LOGOUT_FAILURE";

export const FETCH_APPLICANTS_REQUEST = "FETCH_APPLICANTS_REQUEST";
export const FETCH_APPLICANTS_SUCCESS = "FETCH_APPLICANTS_SUCCESS";
export const FETCH_APPLICANTS_FAILURE = "FETCH_APPLICANTS_FAILURE";

export const DELETE_APPLICANT_REQUEST = "DELETE_APPLICANT_REQUEST";
export const DELETE_APPLICANT_SUCCESS = "DELETE_APPLICANT_SUCCESS";
export const DELETE_APPLICANT_FAILURE = "DELETE_APPLICANT_FAILURE";

// Fetching all applications
export const FETCH_ADMIN_APPS_REQUEST = "FETCH_ADMIN_APPS_REQUEST";
export const FETCH_ADMIN_APPS_SUCCESS = "FETCH_ADMIN_APPS_SUCCESS";
export const FETCH_ADMIN_APPS_FAILURE = "FETCH_ADMIN_APPS_FAILURE";

// Deleting an application
export const DELETE_ADMIN_APP_REQUEST = "DELETE_ADMIN_APP_REQUEST";
export const DELETE_ADMIN_APP_SUCCESS = "DELETE_ADMIN_APP_SUCCESS";
export const DELETE_ADMIN_APP_FAILURE = "DELETE_ADMIN_APP_FAILURE";

// Fetching single application details (For the View Eye icon)
export const FETCH_APP_DETAILS_REQUEST = "FETCH_APP_DETAILS_REQUEST";
export const FETCH_APP_DETAILS_SUCCESS = "FETCH_APP_DETAILS_SUCCESS";
export const FETCH_APP_DETAILS_FAILURE = "FETCH_APP_DETAILS_FAILURE";

export const FETCH_APPLICATION_DETAIL_REQUEST = 'FETCH_APPLICATION_DETAIL_REQUEST';
export const FETCH_APPLICATION_DETAIL_SUCCESS = 'FETCH_APPLICATION_DETAIL_SUCCESS';
export const FETCH_APPLICATION_DETAIL_FAILURE = 'FETCH_APPLICATION_DETAIL_FAILURE';

export const APPROVE_APPLICATION_REQUEST = 'APPROVE_APPLICATION_REQUEST';
export const APPROVE_APPLICATION_SUCCESS = 'APPROVE_APPLICATION_SUCCESS';
export const APPROVE_APPLICATION_FAILURE = 'APPROVE_APPLICATION_FAILURE';

export const REJECT_APPLICATION_REQUEST = 'REJECT_APPLICATION_REQUEST';
export const REJECT_APPLICATION_SUCCESS = 'REJECT_APPLICATION_SUCCESS';
export const REJECT_APPLICATION_FAILURE = 'REJECT_APPLICATION_FAILURE';

export const FETCH_APPLICATION_NOTES_REQUEST = 'FETCH_APPLICATION_NOTES_REQUEST';
export const FETCH_APPLICATION_NOTES_SUCCESS = 'FETCH_APPLICATION_NOTES_SUCCESS';
export const FETCH_APPLICATION_NOTES_FAILURE = 'FETCH_APPLICATION_NOTES_FAILURE';

export const ADD_APPLICATION_NOTE_REQUEST = 'ADD_APPLICATION_NOTE_REQUEST';
export const ADD_APPLICATION_NOTE_SUCCESS = 'ADD_APPLICATION_NOTE_SUCCESS';
export const ADD_APPLICATION_NOTE_FAILURE = 'ADD_APPLICATION_NOTE_FAILURE';

export const DELETE_APPLICATION_NOTE_REQUEST = 'DELETE_APPLICATION_NOTE_REQUEST';
export const DELETE_APPLICATION_NOTE_SUCCESS = 'DELETE_APPLICATION_NOTE_SUCCESS';
export const DELETE_APPLICATION_NOTE_FAILURE = 'DELETE_APPLICATION_NOTE_FAILURE';

// --- APPLICANT (USER) AUTH TYPES ---
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const FETCH_ALL_STATUS_LOGS_REQUEST = 'FETCH_ALL_STATUS_LOGS_REQUEST';
export const FETCH_ALL_STATUS_LOGS_SUCCESS = 'FETCH_ALL_STATUS_LOGS_SUCCESS';
export const FETCH_ALL_STATUS_LOGS_FAILURE = 'FETCH_ALL_STATUS_LOGS_FAILURE';

export const FETCH_STATUS_LOGS_REQUEST = 'FETCH_STATUS_LOGS_REQUEST';
export const FETCH_STATUS_LOGS_SUCCESS = 'FETCH_STATUS_LOGS_SUCCESS';
export const FETCH_STATUS_LOGS_FAILURE = 'FETCH_STATUS_LOGS_FAILURE';

export const FETCH_DASHBOARD_STATS_REQUEST = 'FETCH_DASHBOARD_STATS_REQUEST';
export const FETCH_DASHBOARD_STATS_SUCCESS = 'FETCH_DASHBOARD_STATS_SUCCESS';
export const FETCH_DASHBOARD_STATS_FAILURE = 'FETCH_DASHBOARD_STATS_FAILURE';

export const LOCK_APPLICANT_ACCOUNT_REQUEST = 'LOCK_APPLICANT_ACCOUNT_REQUEST';
export const LOCK_APPLICANT_ACCOUNT_SUCCESS = 'LOCK_APPLICANT_ACCOUNT_SUCCESS';
export const LOCK_APPLICANT_ACCOUNT_FAILURE = 'LOCK_APPLICANT_ACCOUNT_FAILURE';

export const UNLOCK_APPLICANT_ACCOUNT_REQUEST = 'UNLOCK_APPLICANT_ACCOUNT_REQUEST';
export const UNLOCK_APPLICANT_ACCOUNT_SUCCESS = 'UNLOCK_APPLICANT_ACCOUNT_SUCCESS';
export const UNLOCK_APPLICANT_ACCOUNT_FAILURE = 'UNLOCK_APPLICANT_ACCOUNT_FAILURE';

export const ARCHIVE_APPLICANT_ACCOUNT_REQUEST = 'ARCHIVE_APPLICANT_ACCOUNT_REQUEST';
export const ARCHIVE_APPLICANT_ACCOUNT_SUCCESS = 'ARCHIVE_APPLICANT_ACCOUNT_SUCCESS';
export const ARCHIVE_APPLICANT_ACCOUNT_FAILURE = 'ARCHIVE_APPLICANT_ACCOUNT_FAILURE';

export const RESET_APPLICANT_PASSWORD_REQUEST = 'RESET_APPLICANT_PASSWORD_REQUEST';
export const RESET_APPLICANT_PASSWORD_SUCCESS = 'RESET_APPLICANT_PASSWORD_SUCCESS';
export const RESET_APPLICANT_PASSWORD_FAILURE = 'RESET_APPLICANT_PASSWORD_FAILURE';

// redux/type.js — add these:
export const SAVE_FINAL_FORM_STEP_REQUEST = 'SAVE_FINAL_FORM_STEP_REQUEST';
export const SAVE_FINAL_FORM_STEP_SUCCESS = 'SAVE_FINAL_FORM_STEP_SUCCESS';
export const SAVE_FINAL_FORM_STEP_FAILURE = 'SAVE_FINAL_FORM_STEP_FAILURE';

export const FETCH_FORM_PROGRESS_REQUEST = 'FETCH_FORM_PROGRESS_REQUEST';
export const FETCH_FORM_PROGRESS_SUCCESS = 'FETCH_FORM_PROGRESS_SUCCESS';
export const FETCH_FORM_PROGRESS_FAILURE = 'FETCH_FORM_PROGRESS_FAILURE';

export const FETCH_FINAL_FORM_DATA_REQUEST = 'FETCH_FINAL_FORM_DATA_REQUEST';
export const FETCH_FINAL_FORM_DATA_SUCCESS = 'FETCH_FINAL_FORM_DATA_SUCCESS';
export const FETCH_FINAL_FORM_DATA_FAILURE = 'FETCH_FINAL_FORM_DATA_FAILURE';

export const CLEAR_FINAL_FORM_ERROR = 'CLEAR_FINAL_FORM_ERROR';

export const SEND_TO_TABLET_REQUEST = 'SEND_TO_TABLET_REQUEST';
export const SEND_TO_TABLET_SUCCESS = 'SEND_TO_TABLET_SUCCESS';
export const SEND_TO_TABLET_FAILURE = 'SEND_TO_TABLET_FAILURE';

export const UNARCHIVE_APPLICANT_ACCOUNT_REQUEST = 'UNARCHIVE_APPLICANT_ACCOUNT_REQUEST';
export const UNARCHIVE_APPLICANT_ACCOUNT_SUCCESS = 'UNARCHIVE_APPLICANT_ACCOUNT_SUCCESS';
export const UNARCHIVE_APPLICANT_ACCOUNT_FAILURE = 'UNARCHIVE_APPLICANT_ACCOUNT_FAILURE';

// Add these to your types.js
export const FETCH_PRE_EMPLOYMENT_DATA_REQUEST = 'FETCH_PRE_EMPLOYMENT_DATA_REQUEST';
export const FETCH_PRE_EMPLOYMENT_DATA_SUCCESS = 'FETCH_PRE_EMPLOYMENT_DATA_SUCCESS';
export const FETCH_PRE_EMPLOYMENT_DATA_FAILURE = 'FETCH_PRE_EMPLOYMENT_DATA_FAILURE';

export const FETCH_EDUCATION_DATA_REQUEST = 'FETCH_EDUCATION_DATA_REQUEST';
export const FETCH_EDUCATION_DATA_SUCCESS = 'FETCH_EDUCATION_DATA_SUCCESS';
export const FETCH_EDUCATION_DATA_FAILURE = 'FETCH_EDUCATION_DATA_FAILURE';

export const FETCH_AVAILABILITY_DATA_REQUEST = 'FETCH_AVAILABILITY_DATA_REQUEST';
export const FETCH_AVAILABILITY_DATA_SUCCESS = 'FETCH_AVAILABILITY_DATA_SUCCESS';
export const FETCH_AVAILABILITY_DATA_FAILURE = 'FETCH_AVAILABILITY_DATA_FAILURE';

export const FETCH_REFERENCES_DATA_REQUEST = 'FETCH_REFERENCES_DATA_REQUEST';
export const FETCH_REFERENCES_DATA_SUCCESS = 'FETCH_REFERENCES_DATA_SUCCESS';
export const FETCH_REFERENCES_DATA_FAILURE = 'FETCH_REFERENCES_DATA_FAILURE';

export const FETCH_EXPERIENCE_DATA_REQUEST = 'FETCH_EXPERIENCE_DATA_REQUEST';
export const FETCH_EXPERIENCE_DATA_SUCCESS = 'FETCH_EXPERIENCE_DATA_SUCCESS';
export const FETCH_EXPERIENCE_DATA_FAILURE = 'FETCH_EXPERIENCE_DATA_FAILURE';

export const FETCH_DOCUMENTS_DATA_REQUEST = 'FETCH_DOCUMENTS_DATA_REQUEST';
export const FETCH_DOCUMENTS_DATA_SUCCESS = 'FETCH_DOCUMENTS_DATA_SUCCESS';
export const FETCH_DOCUMENTS_DATA_FAILURE = 'FETCH_DOCUMENTS_DATA_FAILURE';

export const FETCH_CERTIFICATION_DATA_REQUEST = 'FETCH_CERTIFICATION_DATA_REQUEST';
export const FETCH_CERTIFICATION_DATA_SUCCESS = 'FETCH_CERTIFICATION_DATA_SUCCESS';
export const FETCH_CERTIFICATION_DATA_FAILURE = 'FETCH_CERTIFICATION_DATA_FAILURE';

export const FETCH_REVIEW_DATA_REQUEST = 'FETCH_REVIEW_DATA_REQUEST';
export const FETCH_REVIEW_DATA_SUCCESS = 'FETCH_REVIEW_DATA_SUCCESS';
export const FETCH_REVIEW_DATA_FAILURE = 'FETCH_REVIEW_DATA_FAILURE';

// Add these types
export const RESEND_EMAIL_REQUEST = 'RESEND_EMAIL_REQUEST';
export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS';
export const RESEND_EMAIL_FAIL = 'RESEND_EMAIL_FAIL';